const FETCH_TODO_ITEM_DETAIL_REQUEST = 'FETCH_TODO_ITEM_DETAIL_REQUEST';
const FETCH_TODO_ITEM_DETAIL_SUCCESS = 'FETCH_TODO_ITEM_DETAIL_SUCCESS';
const FETCH_TODO_ITEM_DETAIL_FAILURE = 'FETCH_TODO_ITEM_DETAIL_FAILURE';

const POST_TODO_ITEM_REQUEST = 'POST_TODO_ITEM_REQUEST';
const POST_TODO_ITEM_SUCCESS = 'POST_TODO_ITEM_SUCCESS';
const POST_TODO_ITEM_FAILURE = 'POST_TODO_ITEM_FAILURE';

const PUT_TODO_ITEM_REQUEST = 'PUT_TODO_ITEM_REQUEST';
const PUT_TODO_ITEM_SUCCESS = 'PUT_TODO_ITEM_SUCCESS';
const PUT_TODO_ITEM_FAILURE = 'PUT_TODO_ITEM_FAILURE';

const DELETE_TODO_ITEM_REQUEST = 'DELETE_TODO_ITEM_REQUEST';
const DELETE_TODO_ITEM_SUCCESS = 'DELETE_TODO_ITEM_SUCCESS';
const DELETE_TODO_ITEM_FAILURE = 'DELETE_TODO_ITEM_FAILURE';

export {
  FETCH_TODO_ITEM_DETAIL_REQUEST,
  FETCH_TODO_ITEM_DETAIL_SUCCESS,
  FETCH_TODO_ITEM_DETAIL_FAILURE,
  POST_TODO_ITEM_REQUEST,
  POST_TODO_ITEM_SUCCESS,
  POST_TODO_ITEM_FAILURE,
  PUT_TODO_ITEM_REQUEST,
  PUT_TODO_ITEM_SUCCESS,
  PUT_TODO_ITEM_FAILURE,
  DELETE_TODO_ITEM_REQUEST,
  DELETE_TODO_ITEM_SUCCESS,
  DELETE_TODO_ITEM_FAILURE,
};
