const FETCH_TODO_LIST_REQUEST = 'FETCH_TODO_LIST_REQUEST';
const FETCH_TODO_LIST_SUCCESS = 'FETCH_TODO_LIST_SUCCESS';
const FETCH_TODO_LIST_FAILURE = 'FETCH_TODO_LIST_FAILURE';

export { FETCH_TODO_LIST_REQUEST, FETCH_TODO_LIST_SUCCESS, FETCH_TODO_LIST_FAILURE };
